name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: magick cache
      id: magickcache
      uses: actions/cache@v2
      with:
        path: magickbin
    - name: Install magick
      if: steps.magickcache.outputs.cache-hit != 'true'
      run:
        set -e
        mkdir -p magickbin
        curl -o magickcbin/magick https://imagemagick.org/download/binaries/magick
        chmod +x magickbin/magick
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.1
      with:
        go-version: "1.14.3"
    - name: Run tests
      run: |
        set -e
        export PATH=${PWD}/magickbin:${PATH}
        go test ./... -v
    - name: Run tests
      run: |
        set -e
        mkdir -p dist 
        cd cmd/microavatar
        go build -o ../../dist/microavatar
    - uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: dist/microavatar
