name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.3
      with:
        go-version: "1.16.2"
    - name: Install magick
      run: |
        set -e
        mkdir -p magickbin
        curl -o magickbin/magick https://imagemagick.org/download/binaries/magick
        chmod +x magickbin/magick
    - name: Run tests
      run: |
        set -e
        chmod +x magickbin/magick
        export PATH=${PWD}/magickbin:${PATH}
        go test ./... -v
    - name: Run tests
      run: |
        set -e
        mkdir -p dist 
        cd cmd/microavatar
        go build -o ../../dist/microavatar
    - uses: actions/upload-artifact@v2
      if: "${{ github.ref == 'refs/heads/main' }}"
      with:
        name: linux-binary
        path: dist/microavatar
